### ISSUE TITLE
Can't save

### ISSUE THREAD

**Issue by jvolker** [therewasaguy/p5js-webIDE#112]
On http://p5ide.herokuapp.com I tried to save the starter example as logged in user on Github. It asked me for a name and I typed in `test`. It left me with this in the top of the page for a few minutes: 

![image](https://cloud.githubusercontent.com/assets/546852/14622802/f0835464-05cc-11e6-8194-065ac0d0359b.png)

And then the messages switches to: `There was an error saving. Please try again later` … or similar.

**Comment by therewasaguy** [comment]
thanks for the headsup @jvolker, this should be fixed now—try it and let me know?

**Comment by jvolker** [comment]
Tried it. Unfortunately it's still not working and the same problem occurs. I'm on Firefox, if that helps.

**Comment by therewasaguy** [comment]
Ok it should work, for real now!

Projects are saved in a MongoDB. It's running on the free-tier at [mlab](https://mlab.com). Mlab recently changed their name (from mongolab). So at first I thought that updating the path to the database with their new domain name would fix this, but it didn't help.

Then it turned out that the db had exceeded mlab's free tier limit, so new projects could not be saved to memory. 

I just migrated the database + did some major cleanup (removed all duplicate p5.js, p5.sound and p5.dom files so they all point to the same file ID's).

You should be able to save now, and access all previous projects (they are also all backed up just in case).

Please comment here if there are any issues with saving or accessing saved files.

**Comment by jvolker** [comment]
Brilliant! Works like a charme. Thanks @therewasaguy for the quick fix.

It seems to be a really nice tool! I'm going try it today in my classes and ask the students to share their code on the platform. That makes 50 more testers.

**Comment by therewasaguy** [comment]
Thanks @jvolker! Let us know how it goes. Made a small update today where all new projects pull p5 library files from the CDN, so we should have plenty of room for a while.
